@host=http://localhost:5065
GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNGY5MTFhZS01Y2M5LTQ2Y2ItYTBhZS00ZGNmMTc1MmFjMjUiLCJnaXZlbl9uYW1lIjoiRHlsYW4iLCJmYW1pbHlfbmFtZSI6IkNoZW4iLCJqdGkiOiI3MDhjMGZiZS0xOWYyLTQxMTUtOGExNy03MjU5MzE1N2QyMDgiLCJleHAiOjE3MDc2NTI0NTEsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.ivxw9ARlcOCzsBU_28iMjck3ru6sFXE1Kmad40e_dOI